# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1732b0b679589ef032d4013689493149f96cf9da3ff2525bf44f401e942dcabbb8aa7e3d767320972a68dc3c189753bbbfc8769bf3ba782ace240458484cc28f

test:
  secret_key_base: e6df78066510f7d899e726e5c8b3bd8ed6e026e380a331bed2e2a9512ae858639a6f0e6f03bff97ab0e9c92c5a513e906e577974073382b68735933cfd244ebc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
